name: "inference"
backend: "onnxruntime"
default_model_filename: "model.onnx"
max_batch_size: 64

input [
  {
    name: "pixel_values",
    data_type: TYPE_FP32,
    dims: [ -1, -1, -1 ]
  }
],
output [
  {
    name: "logits",
    data_type: TYPE_FP32,
    dims: [ 1000 ]
  }
]

version_policy: { specific { versions: [1] }}
instance_group {
    count: 1
    kind: KIND_CPU
}
