{
 "title": "Tritonserver Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Inference request success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nv_inference_request_success{model=\"inference\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_inference_request_success{model=\"postprocess\"}",
     "legendFormat": "__auto"
    },
    {},
    {
     "expr": "nv_inference_request_success{model=\"preprocess\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_inference_request_success{model=\"rubert\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "nv_inference_request_duration_us{model=\"inference\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_inference_request_duration_us{model=\"postprocess\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_inference_request_duration_us{model=\"preprocess\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_inference_request_duration_us{model=\"rubert\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference pending count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nv_inference_pending_request_count{model=\"inference\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_inference_pending_request_count{model=\"postprocess\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_inference_pending_request_count{model=\"preprocess\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_inference_pending_request_count{model=\"rubert\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference queue duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "nv_inference_queue_duration_us{model=\"inference\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_inference_queue_duration_us{model=\"postprocess\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_inference_queue_duration_us{model=\"preprocess\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_inference_queue_duration_us{model=\"rubert\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "nv_cpu_utilization{job=\"triton\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "nv_cpu_memory_used_bytes{job=\"triton\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_cpu_memory_total_bytes{job=\"triton\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "nv_gpu_memory_used_bytes{job=\"triton\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_gpu_memory_total_bytes{job=\"triton\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Predictions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_class_labels{class=\"admiration\"}",
     "legendFormat": "{{admiration}} admiration"
    },
    {
     "expr": "prediction_class_labels{class=\"amusement\"}",
     "legendFormat": "{{label_name}} amusement"
    },
    {
     "expr": "prediction_class_labels{class=\"anger\"}",
     "legendFormat": "{{label_name}} anger"
    },
    {
     "expr": "prediction_class_labels{class=\"annoyance\"}",
     "legendFormat": "{{label_name}} annoyance"
    },
    {
     "expr": "prediction_class_labels{class=\"approval\"}",
     "legendFormat": "{{label_name}}approval"
    },
    {
     "expr": "prediction_class_labels{class=\"caring\"}",
     "legendFormat": "{{label_name}}caring"
    },
    {
     "expr": "prediction_class_labels{class=\"confusion\"}",
     "legendFormat": "{{label_name}}confusion"
    },
    {
     "expr": "prediction_class_labels{class=\"curiosity\"}",
     "legendFormat": "{{label_name}}curiosity"
    },
    {
     "expr": "prediction_class_labels{class=\"desire\"}",
     "legendFormat": "{{label_name}}desire"
    },
    {
     "expr": "prediction_class_labels{class=\"disappointment\"}",
     "legendFormat": "{{label_name}}disappointment"
    },
    {
     "expr": "prediction_class_labels{class=\"disapproval\"}",
     "legendFormat": "{{label_name}}disapproval"
    },
    {
     "expr": "prediction_class_labels{class=\"disgust\"}",
     "legendFormat": "{{label_name}}disgust"
    },
    {
     "expr": "prediction_class_labels{class=\"embarrassment\"}",
     "legendFormat": "{{label_name}}embarrassment"
    },
    {
     "expr": "prediction_class_labels{class=\"excitement\"}",
     "legendFormat": "{{label_name}}excitement"
    },
    {
     "expr": "prediction_class_labels{class=\"fear\"}",
     "legendFormat": "{{label_name}}fear"
    },
    {
     "expr": "prediction_class_labels{class=\"gratitude\"}",
     "legendFormat": "{{label_name}}gratitude"
    },
    {
     "expr": "prediction_class_labels{class=\"grief\"}",
     "legendFormat": "{{label_name}}grief"
    },
    {
     "expr": "prediction_class_labels{class=\"joy\"}",
     "legendFormat": "{{label_name}}joy"
    },
    {
     "expr": "prediction_class_labels{class=\"love\"}",
     "legendFormat": "{{label_name}}love"
    },
    {
     "expr": "prediction_class_labels{class=\"nervousness\"}",
     "legendFormat": "{{label_name}}nervousness"
    },
    {
     "expr": "prediction_class_labels{class=\"neutral\"}",
     "legendFormat": "{{label_name}}neutral"
    },
    {
     "expr": "prediction_class_labels{class=\"optimism\"}",
     "legendFormat": "{{label_name}}optimism"
    },
    {
     "expr": "prediction_class_labels{class=\"pride\"}",
     "legendFormat": "{{label_name}}pride"
    },
    {
     "expr": "prediction_class_labels{class=\"realization\"}",
     "legendFormat": "{{label_name}}realization"
    },
    {
     "expr": "prediction_class_labels{class=\"relief\"}",
     "legendFormat": "{{label_name}}relief"
    },
    {
     "expr": "prediction_class_labels{class=\"remorse\"}",
     "legendFormat": "{{label_name}}remorse"
    },
    {
     "expr": "prediction_class_labels{class=\"sadness\"}",
     "legendFormat": "{{label_name}}sadness"
    },
    {
     "expr": "prediction_class_labels{class=\"surprise\"}",
     "legendFormat": "{{label_name}}surprise"
    }
   ]
  }
 ]
}